[toolchain]
channel = "rust-dist" # Should be a compiler build from this PR: https://github.com/rust-lang/rust/pull/162426
#channel = "nightly-2026-08-07"
#components = ["rust-src", "rustc-dev", "llvm-tools", "rustfmt"]
#profile = "minimal"
